module.exports.descriptors = [
    'Pensiunea',
    'Vila',
    'Hotelul',
    'Casa de oaspeți',
    'Camping',
    'Cabana',
    'Sanatoriul',
    'Conacul',
    'Hanul',
    'Casă de vacanță',
    'Resortul',
    'Bungaloul',
    'Castelul',
    'Refugiul',
    'Condo',
    'Motelul',
    'Cortul',
    'Așezarea turistică',
    'Pensionul',
    'Complexul turistic',
    'Casa rurală',
    'Căminul turistului',
    'Mănăstirea',
    'Motelul'
]

module.exports.places = [
    'Linistita',
    'Cozy',
    'Elegantă',
    'Natură',
    'Serena',
    'Frumoasă',
    'Rurală',
    'Pitorescă',
    'Montană',
    'Lacustră',
    'Verde',
    'Izolată',
    'Litorală',
    'Tradițională',
    'Rustică',
    'Istorică',
    'Luxoasă',
    'Relaxantă',
    'Panoramică',
    'Ecologică',
    'În aer liber',
    'Refugiu',
    'Confortabilă',
    'Misterioasă',
    'Modernă'
]
